### ISSUE TITLE
TypeError: base64 is not a function

### ISSUE THREAD

**Issue by anton-johansson** [gillstrom/swish-qr-cli#1]
```sh
➜ swish-qr
? What is the recipients phone number? 123000000
? How much money do you want to send? 123
? Do you want to send a message? Hello
? Which fields do you want to lock? Number, Amount
TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at generateImage (/home/anton/.nvm/versions/node/v5.3.0/lib/node_modules/swish-qr-cli/cli.js:40:17)
    at /home/anton/.nvm/versions/node/v5.3.0/lib/node_modules/swish-qr-cli/cli.js:73:4
    at process._tickCallback (node.js:382:9)
```

```sh
➜ swish-qr --version
1.0.1

➜ node -v
v5.3.0

➜ npm -v               
3.5.3

➜ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```

**Comment by kevva** [comment]
Could you try upgrading to a stable Node.js version and try again? Odd version numbers (like `5`) are unstable.

**Comment by anton-johansson** [comment]
Did not know that! Worked better with `8`, thanks.

**Comment by kevva** [comment]
Yeah, `Buffer.from` was backported to `4.5.0` (and probably `5.5.0` or something). Should've been backported all the way or just introduced in `6.0.0`, but whatever.
